"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const animalBuilder_1 = require("./animalBuilder");
const animalBuilder_2 = require("./animalBuilder");
const animalBuilder_3 = require("./animalBuilder");
const animalBuilder = new animalBuilder_1.AnimalBuilder(animalBuilder_2.Dog);
animalBuilder.setType("dog").setSound("bark");
let dog = animalBuilder.getInstance();
console.log("dog", dog, dog.Bark());
const animalBuilder2 = new animalBuilder_1.AnimalBuilder(animalBuilder_3.Cat);
let cat = animalBuilder2.getInstance();
animalBuilder2.setType("cat").setSound("miau");
console.log("cat", cat, cat.Miau());
